common:
  - docker_deno: &deno
      - docker#v5.10.0:
          image: "denoland/deno:{{matrix}}"

steps:
  - group: ":deno: deno [latest]"
    key: "deno-latest"
    steps:
      - label: "deno lint"
        command: "deno lint"
        matrix:
          - "latest"
          - "1.42.1"
        plugins: 
          - *deno

  - group: ":godmode: test projects"
    key: "test-projects"
    steps:
      - trigger: "test-project-minimal"
        label: ":godmode: test project minimal"
        build:
          message: "test runreal ${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}"
          env: 
            RUNREAL_FROM_SOURCE: true
            RUNREAL_FROM_REF: $BUILDKITE_COMMIT
