- trigger: "test-project-minimal"
  label: ":godmode: test project minimal"
  build:
    message: "test runreal ${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}"
    env: 
      RUNREAL_FROM_SOURCE: true
      RUNREAL_FROM_REF: $BUILDKITE_BRANCH